### ISSUE TITLE
Interface in Edge

### ISSUE THREAD

**Issue by javiavid** [skyiea/rememberry-i10n#3]
In the Edge browser the interface is not displayed correctly and it is not possible to export the Deck because the Actions button does not appear.
![image](https://user-images.githubusercontent.com/7627504/107242185-029ed100-6a2c-11eb-90de-30d660e7c857.png)

![image](https://user-images.githubusercontent.com/7627504/107242256-12b6b080-6a2c-11eb-979f-5cc04dd0cd0e.png)

**Comment by skyiea** [comment]
At the moment we don't support browsers other than Google Chrome.
